import frm24 from "../assets/images/frame 24.png";
import frm25 from "../assets/images/frame 25.png";
import frm26 from "../assets/images/frame 26.png";
import frm27 from "../assets/images/frame 27.png";

const Prods = [
  {
    id: 1,
    image: frm24,
    disc: "Denim Peshawari Chappal",
    oldprice: 5000,
    saleprice: 4500,
    rating: 4.9,
    ratingNum: 23,
    color: "black",
    size: "M",
    brand: "Brand 01",
  },
  {
    id: 2,
    image: frm25,
    disc: "Denim Peshawari Chappal",
    oldprice: 5200,
    saleprice: 4700,
    rating: 4.8,
    ratingNum: 18,
    color: "yellow",
    size: "L",
    brand: "Brand 02",
  },
  {
    id: 3,
    image: frm26,
    disc: "Denim Peshawari Chappal",
    oldprice: 4800,
    saleprice: 4300,
    rating: 4.7,
    ratingNum: 16,
    color: "black",
    size: "S",
    brand: "Brand 01",
  },
  {
    id: 4,
    image: frm27,
    disc: "Denim Peshawari Chappal",
    oldprice: 5100,
    saleprice: 4600,
    rating: 4.6,
    ratingNum: 14,
    color: "red",
    size: "XL",
    brand: "Brand 03",
  },
  {
    id: 5,
    image: frm24,
    disc: "Denim Peshawari Chappal",
    oldprice: 5300,
    saleprice: 4800,
    rating: 4.5,
    ratingNum: 11,
    color: "blue",
    size: "XXL",
    brand: "Brand 04",
  },
  {
    id: 6,
    image: frm25,
    disc: "Denim Peshawari Chappal",
    oldprice: 5000,
    saleprice: 4400,
    rating: 4.8,
    ratingNum: 19,
    color: "black",
    size: "M",
    brand: "Brand 02",
  },
  {
    id: 7,
    image: frm26,
    disc: "Denim Peshawari Chappal",
    oldprice: 4900,
    saleprice: 4200,
    rating: 4.7,
    ratingNum: 15,
    color: "yellow",
    size: "S",
    brand: "Brand 01",
  },
  {
    id: 8,
    image: frm27,
    disc: "Denim Peshawari Chappal",
    oldprice: 5400,
    saleprice: 4900,
    rating: 4.6,
    ratingNum: 13,
    color: "red",
    size: "L",
    brand: "Brand 03",
  },
  {
    id: 9,
    image: frm24,
    disc: "Denim Peshawari Chappal",
    oldprice: 5600,
    saleprice: 5100,
    rating: 4.9,
    ratingNum: 27,
    color: "blue",
    size: "XL",
    brand: "Brand 04",
  },
  {
    id: 10,
    image: frm25,
    disc: "Denim Peshawari Chappal",
    oldprice: 4700,
    saleprice: 4100,
    rating: 4.6,
    ratingNum: 12,
    color: "black",
    size: "M",
    brand: "Brand 01",
  },
  {
    id: 11,
    image: frm26,
    disc: "Denim Peshawari Chappal",
    oldprice: 5200,
    saleprice: 4600,
    rating: 4.8,
    ratingNum: 20,
    color: "yellow",
    size: "XXL",
    brand: "Brand 02",
  },
  {
    id: 12,
    image: frm27,
    disc: "Denim Peshawari Chappal",
    oldprice: 5500,
    saleprice: 5000,
    rating: 4.7,
    ratingNum: 17,
    color: "red",
    size: "L",
    brand: "Brand 03",
  },
];

export default Prods;
